package com.zy.study.entity;
  
import java.util.Date;
import java.math.BigDecimal; 
import java.util.ArrayList;
import java.util.List;

/**
 *  * @ClassName: TbTaxpayer 
 This code was generated by Will at 2017-07-12 16:51:14
 * @autoInfo by Apexes Studio with Java runtime 1.7 or later and Spring 2.5 or later
 * @autoInfo CopyRright (c) www.ca-css.com 2014   
 * 
 */
public class TbTaxpayer implements java.io.Serializable {  
	private static final long serialVersionUID = 3L;

	private BigDecimal taxpayerUid;//TAXPAYER_UID
	private String nameInEnglish;//NAME_IN_ENGLISH
	private String nameInSecondLang;//NAME_IN_SECOND_LANG
	private String tin;//TIN
	private BigDecimal branchId;//BRANCH_ID
	private String taxpayerCategory;//TAXPAYER_CATEGORY
	private String taxpayerType;//TAXPAYER_TYPE
	private String registeredMagisterialState;//REGISTERED_MAGISTERIAL_STATE
	private String tinOffice;//TIN_OFFICE
	private String state;//STATE
	private String city;//CITY
	private String locality;//LOCALITY
	private String idType;//ID_TYPE
	private String idNumber;//ID_NUMBER
	private String telphone;//TELPHONE
	private String physicalAddress;//PHYSICAL_ADDRESS
	private String postalAddress;//POSTAL_ADDRESS
	private String mainTaxpableActivity;//MAIN_TAXPABLE_ACTIVITY
	private String preferredLanguage;//PREFERRED_LANGUAGE
	private String registrationOffice;//REGISTRATION_OFFICE
	private Date sysRegisteredTime;//SYS_REGISTERED_TIME
	private String turnoversize;//TURNOVERSIZE
	private String status;//STATUS

	private String statusShow;
	private String allowForeignCurrency;

	public String getAllowForeignCurrency() {
		return allowForeignCurrency;
	}

	public void setAllowForeignCurrency(String allowForeignCurrency) {
		this.allowForeignCurrency = allowForeignCurrency;
	}

	public String getStatusShow() {
		return statusShow;
	}


	public void setStatusShow(String statusShow) {
		this.statusShow = statusShow;
	}


	/**
	 * copyFrom
	 * @param src
	 */
	public void copyFrom(TbTaxpayer src){
		this.taxpayerUid=src.taxpayerUid;//TAXPAYER_UID
		this.nameInEnglish=src.nameInEnglish;//NAME_IN_ENGLISH
		this.nameInSecondLang=src.nameInSecondLang;//NAME_IN_SECOND_LANG
		this.tin=src.tin;//TIN
		this.branchId=src.branchId;//BRANCH_ID
		this.taxpayerCategory=src.taxpayerCategory;//TAXPAYER_CATEGORY
		this.taxpayerType=src.taxpayerType;//TAXPAYER_TYPE
		this.registeredMagisterialState=src.registeredMagisterialState;//REGISTERED_MAGISTERIAL_STATE
		this.tinOffice=src.tinOffice;//TIN_OFFICE
		this.state=src.state;//STATE
		this.city=src.city;//CITY
		this.locality=src.locality;//LOCALITY
		this.idType=src.idType;//ID_TYPE
		this.idNumber=src.idNumber;//ID_NUMBER
		this.telphone=src.telphone;//TELPHONE
		this.physicalAddress=src.physicalAddress;//PHYSICAL_ADDRESS
		this.postalAddress=src.postalAddress;//POSTAL_ADDRESS
		this.mainTaxpableActivity=src.mainTaxpableActivity;//MAIN_TAXPABLE_ACTIVITY
		this.preferredLanguage=src.preferredLanguage;//PREFERRED_LANGUAGE
		this.registrationOffice=src.registrationOffice;//REGISTRATION_OFFICE
		this.sysRegisteredTime=src.sysRegisteredTime;//SYS_REGISTERED_TIME
		this.turnoversize=src.turnoversize;//TURNOVERSIZE
		this.status=src.status;//STATUS
		}


	/**
	 * 	 */
			public BigDecimal getTaxpayerUid(){
		return this.taxpayerUid;
	}
	
	/**
	 * 	 */
	public void setTaxpayerUid(BigDecimal taxpayerUid){
		this.taxpayerUid = taxpayerUid;
	}
	/**
	 * 	 */
			public String getNameInEnglish(){
		return this.nameInEnglish;
	}
	
	/**
	 * 	 */
	public void setNameInEnglish(String nameInEnglish){
		this.nameInEnglish = nameInEnglish;
	}
	/**
	 * 	 */
			public String getNameInSecondLang(){
		return this.nameInSecondLang;
	}
	
	/**
	 * 	 */
	public void setNameInSecondLang(String nameInSecondLang){
		this.nameInSecondLang = nameInSecondLang;
	}
	/**
	 * 	 */
			public String getTin(){
		return this.tin;
	}
	
	/**
	 * 	 */
	public void setTin(String tin){
		this.tin = tin;
	}
	/**
	 * 	 */
			public BigDecimal getBranchId(){
		return this.branchId;
	}
	
	/**
	 * 	 */
	public void setBranchId(BigDecimal branchId){
		this.branchId = branchId;
	}
	/**
	 * 	 */
			public String getTaxpayerCategory(){
		return this.taxpayerCategory;
	}
	
	/**
	 * 	 */
	public void setTaxpayerCategory(String taxpayerCategory){
		this.taxpayerCategory = taxpayerCategory;
	}
	/**
	 * 	 */
			public String getTaxpayerType(){
		return this.taxpayerType;
	}
	
	/**
	 * 	 */
	public void setTaxpayerType(String taxpayerType){
		this.taxpayerType = taxpayerType;
	}
	/**
	 * 	 */
			public String getRegisteredMagisterialState(){
		return this.registeredMagisterialState;
	}
	
	/**
	 * 	 */
	public void setRegisteredMagisterialState(String registeredMagisterialState){
		this.registeredMagisterialState = registeredMagisterialState;
	}
	/**
	 * 	 */
			public String getTinOffice(){
		return this.tinOffice;
	}
	
	/**
	 * 	 */
	public void setTinOffice(String tinOffice){
		this.tinOffice = tinOffice;
	}
	/**
	 * 	 */
			public String getState(){
		return this.state;
	}
	
	/**
	 * 	 */
	public void setState(String state){
		this.state = state;
	}
	/**
	 * 	 */
			public String getCity(){
		return this.city;
	}
	
	/**
	 * 	 */
	public void setCity(String city){
		this.city = city;
	}
	/**
	 * 	 */
			public String getLocality(){
		return this.locality;
	}
	
	/**
	 * 	 */
	public void setLocality(String locality){
		this.locality = locality;
	}
	/**
	 * 	 */
			public String getIdType(){
		return this.idType;
	}
	
	/**
	 * 	 */
	public void setIdType(String idType){
		this.idType = idType;
	}
	/**
	 * 	 */
			public String getIdNumber(){
		return this.idNumber;
	}
	
	/**
	 * 	 */
	public void setIdNumber(String idNumber){
		this.idNumber = idNumber;
	}
	/**
	 * 	 */
			public String getTelphone(){
		return this.telphone;
	}
	
	/**
	 * 	 */
	public void setTelphone(String telphone){
		this.telphone = telphone;
	}
	/**
	 * 	 */
			public String getPhysicalAddress(){
		return this.physicalAddress;
	}
	
	/**
	 * 	 */
	public void setPhysicalAddress(String physicalAddress){
		this.physicalAddress = physicalAddress;
	}
	/**
	 * 	 */
			public String getPostalAddress(){
		return this.postalAddress;
	}
	
	/**
	 * 	 */
	public void setPostalAddress(String postalAddress){
		this.postalAddress = postalAddress;
	}
	/**
	 * 	 */
			public String getMainTaxpableActivity(){
		return this.mainTaxpableActivity;
	}
	
	/**
	 * 	 */
	public void setMainTaxpableActivity(String mainTaxpableActivity){
		this.mainTaxpableActivity = mainTaxpableActivity;
	}
	/**
	 * 	 */
			public String getPreferredLanguage(){
		return this.preferredLanguage;
	}
	
	/**
	 * 	 */
	public void setPreferredLanguage(String preferredLanguage){
		this.preferredLanguage = preferredLanguage;
	}
	/**
	 * 	 */
			public String getRegistrationOffice(){
		return this.registrationOffice;
	}
	
	/**
	 * 	 */
	public void setRegistrationOffice(String registrationOffice){
		this.registrationOffice = registrationOffice;
	}
	/**
	 * 	 */
	
	/**
	 * 	 */
	public void setSysRegisteredTime(Date sysRegisteredTime){
		this.sysRegisteredTime = sysRegisteredTime;
	}
	/**
	 * 	 */
			public String getTurnoversize(){
		return this.turnoversize;
	}
	
	/**
	 * 	 */
	public void setTurnoversize(String turnoversize){
		this.turnoversize = turnoversize;
	}
	/**
	 * 	 */
			public String getStatus(){
		return this.status;
	}
	
	/**
	 * 	 */
	public void setStatus(String status){
		this.status = status;
	}

 
}