package com.zy.study.entity;
  
import java.util.Date;
import java.math.BigDecimal; 
import java.util.ArrayList;
import java.util.List;



/**
 *  * @ClassName: TbTaxpayerCriteria 
 This code was generated by Will at 2017-07-12 16:51:14
 * @autoInfo by Apexes Studio with Java runtime 1.7 or later and Spring 2.5 or later
 * @autoInfo CopyRright (c) www.ca-css.com 2014   
 * 
 */
public class TbTaxpayerCriteria  {   


}