package com.zy.study.mapper;

import java.math.BigDecimal;
import java.util.List;

import com.zy.study.entity.TbTaxpayer;
import com.zy.study.entity.TbTaxpayerCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
/**
 *   * @ClassName: TbTaxpayer 
 This code was generated by Will at 2017-07-12 16:51:14
 * @autoInfo by Apexes Studio with Java runtime 1.7 or later and Spring 2.5 or later
 * @autoInfo CopyRright (c) www.ca-css.com 2014   
 @autodate 2017-07-12 16:51:14
 * 
 */
public interface TbTaxpayerMapper {

	List<TbTaxpayer> selectByExample(TbTaxpayerCriteria tbTaxpayerCriteria);

  
}